services:
  postgres:
    image: postgres:16-alpine
    container_name: chat-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-dev-network

networks:
  chat-dev-network:
    driver: bridge

volumes:
  postgres-dev-data: 